#!/bin/sh
#
#	tests

# 114 is lengthy >13m

for i in `seq 200`
do
	case $i in
	10|114|120|121|133|149|163|180|182|183|184|195)
		# function add_to_summary, file tag.c, line 382. Abort trap: 6
		continue;;
	114)
		continue;;	# runs more than 13 minutes
	110)
		continue;;	# runs a very long time
	esac

	tag "(100)^$i" 3 00 1101 | tee tests/$i.new || {
		echo "error in test $i" 1>&2
		continue
	}

	if [ ! -s tests/$i ]
	then
		mv tests/$i.new tests/$i
	else
		oldline=`sed 1q tests/$i`
		set $oldline
		shift; shift
		old=`echo $*`

		newline=`sed 1q tests/$i.new`
		set $newline
		shift; shift
		new=`echo $*`

		if [ "$new" != "$old" ]
		then
			echo was $oldline
		fi
	fi
done
