#!/bin/sh
#
prog=findcycle
usage="$prog [tagoutput]"
#
#	Find mu and lambda, the start and length, of cycles from
#	tag debugging output.  E.g.:
#
#	tag -d "(100)^109" 3 00 1101 | findloop
#
#	writes mu and lambda to stdout.  Also how many repeats were encountered
#	before termination.

sort -k3 -k1n $* |	# bring patterns together, earliest first
uniq -c -f2 | 		# count them
grep -v '^ *1 ' |		# those appearing once aren't in the cycle
sort -k2n |		# earliest first
awk '
NR == 1 {
	mu=$2
	repeats=$1
	next }
{	next }
END {	lambda=NR
	print mu, lambda, repeats
}'
